[package]
name = "wasmer-compiler-cranelift-py"
version = "0.5.0"
authors = ["Wasmer Engineering Team <engineering@wasmer.io>"]
edition = "2018"
description = "Python extension to run WebAssembly binaries"
readme = "README.md"
repository = "https://github.com/wasmerio/wasmer-python"
keywords = ["python", "extension", "webassembly"]
categories = ["wasm"]
publish = false

[lib]
name = "wasmer_compiler_cranelift"
crate-type = ["cdylib"]

[dependencies]
wasmer-common-py = { path = "../common/" }
wasmer-compiler-cranelift = { git = "https://github.com/wasmerio/wasmer", branch = "master" }
pyo3 = { version = "0.11", features = ["extension-module"] }

[package.metadata.maturin]
project-url = [
    "Source Code, https://github.com/wasmerio/wasmer-python/",
    "Bug Tracker, https://github.com/wasmerio/wasmer-python/issues",
    "Documentation, https://github.com/wasmerio/wasmer-python/",
]
classifier = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Rust",
    "Topic :: Software Development",
    "Topic :: Software Development :: Compilers",
    "Topic :: Software Development :: Interpreters",
    "Topic :: Software Development :: Interpreters",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]