status = [
    "Test (ubuntu-latest, 3.6)",
    "Test (ubuntu-latest, 3.7)",
    "Test (ubuntu-latest, 3.8)",
    "Test (macos-latest, 3.6)",
    "Test (macos-latest, 3.7)",
    "Test (macos-latest, 3.8)",
]
required_approvals = 0
timeout_sec = 900
delete_merged_branches = true 