[package]
name = "python-ext-wasm"
version = "0.1.0"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]
edition = "2018"

[lib]
name = "wasm"
crate-type = ["cdylib"]

[dependencies]
cpython = { version = "0.2", features = ["extension-module"] }
wasmer-runtime = { git = "https://github.com/wasmerio/wasmer", branch = "master" }