[workspace]
members = [
    "packages/api",
    "packages/common",
    "packages/compiler-cranelift",
    "packages/compiler-llvm",
    "packages/compiler-singlepass",
]
exclude = [
    "packages/any",
]