[package]
name = "python-ext-wasm"
version = "0.1.2"
authors = ["Ivan Enderlin <ivan.enderlin@hoa-project.net>"]
edition = "2018"
description = "Python extension to run WebAssembly binaries"
readme = "README.md"
repository = "https://github.com/wasmerio/python-ext-wasm"
keywords = ["python", "extension", "webassembly"]
categories = ["wasm"]

[lib]
name = "wasm"
crate-type = ["cdylib"]

[dependencies]
cpython = { version = "0.2", features = ["extension-module"] }
wasmer-runtime = { git = "https://github.com/wasmerio/wasmer", branch = "master" }

[package.metadata.pyo3-pack]
classifier = [
    "Programming Language :: Python",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]