version: 2.1
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: rustup default nightly
      - restore_cache:
          keys:
            - v2-linux-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v2-linux-{{ arch }}
      - run:
          name: Install just
          command: |
            test -f /usr/local/cargo/bin/just || cargo install just
      - run:
          name: Install pyenv
          command: |
            test -d /home/circleci/.pyenv || curl https://pyenv.run | bash
      - run:
          name: Install Python versions 3.5.7, 3.6.8, and 3.7.3
          command: |
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            test -d /home/circleci/.pyenv/versions/3.5.7/bin || pyenv install 3.5.7
            test -d /home/circleci/.pyenv/versions/3.6.8/bin || pyenv install 3.6.8
            test -d /home/circleci/.pyenv/versions/3.7.3/bin || pyenv install 3.7.3
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/release/.fingerprint
            - target/release/build
            - target/release/deps
            - /home/circleci/.pyenv
          key: v2-linux-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Prelude
          command: |
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            export PATH="/usr/local/cargo/bin:$PATH"
            export PATH="/home/circleci/.pyenv/versions/3.7.3/bin/:$PATH"
            just prelude
      - run:
          name: Compile the extension
          command: |
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            export PATH="/usr/local/cargo/bin:$PATH"
            export PATH="/home/circleci/.pyenv/versions/3.7.3/bin/:$PATH"
            source .env/bin/activate
            just rust
      - run:
          name: Test the extension
          command: |
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            export PATH="/usr/local/cargo/bin:$PATH"
            export PATH="/home/circleci/.pyenv/versions/3.7.3/bin/:$PATH"
            source .env/bin/activate
            just test
  deploy:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: rustup default nightly
      - restore_cache:
          keys:
            - v2-linux-{{ arch }}-{{ checksum "Cargo.lock" }}
            - v2-linux-{{ arch }}
      - run:
          name: Publish the extension
          command: |
            export PATH="/home/circleci/.pyenv/bin:$PATH"
            export PATH="/usr/local/cargo/bin:$PATH"
            export PATH="/home/circleci/.pyenv/versions/3.7.3/bin/:$PATH"
            export PATH="/home/circleci/.pyenv/versions/3.6.8/bin/:$PATH"
            export PATH="/home/circleci/.pyenv/versions/3.5.7/bin/:$PATH"
            source .env/bin/activate
            pyo3-pack publish -i python3.7 python3.6 python3.5 -u wasmer

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
